[package]
name = "computorv1"
version = "0.1.0"
authors = ["cchudant <skybt@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
